Сегодня тебе нужно выполнить задачу от руководительницы отдела контент-маркетинга новой онлайн-школы английского языка. Она хочет составить ТЗ копирайтеру на написание постов, но для этого ей нужно знать, какие типы постов популярны. За завтраком вы с ней обсуждали твое последнее занятие с курса Python, где мы парсили страницы сообществ ВК, и у вас появилась идея – проанализировать самые успешные посты известной онлайн-школы Skyeng  в [сообществе Skyeng в ВК](https://vk.com/skyeng).

Теперь перед тобой стоит задача – выгрузить маркетологам для анализа 50 самых популярных постов за все время существования сообщества. Метрику популярности будем считать как сумму лайков, репостов и комментариев к каждому посту. Если останется время, для дополнительного анализа выгрузи все комментарии к этим постам в отдельный файл.

In [1]:
# читаем токен из файла my_own_token.py, куда мы сохранили access_token
from my_token import my_token as token



__Сформируем запрос, который получает 100 записей со стены сообщества__

In [47]:
import requests 
import pandas as pd
import json

In [49]:
url = 'https://api.vk.com/method/wall.get'
params = {
        'domain': 'skyeng',
        'access_token': token,
        'v':'5.131',
        'count': 100,
        'filter': 'all'
      
    }
    
req = requests.get(url, params=params)
res = req.json()

print('Кол-во записей:', len(pd.DataFrame(res['response'])))

Кол-во записей: 100



Выгружаем в переменную `posts` все записи сообщества

In [50]:
import time
offset = 0
max_count = 100
posts = pd.DataFrame()
while True:
    url = 'https://api.vk.com/method/wall.get'
    params = {
        'domain': 'skyeng',
        'access_token': token,
        'v':'5.131',
        'count': max_count,
        'offset': offset
      
    }
    req = requests.get(url, params=params)
    res = req.json()
    if len (res['response']['items'])!=0:
        posts = pd.concat([posts, pd.DataFrame(res['response']['items'])])
    else:
        break
    print('Уже скачано', offset, 'записей')
    offset = offset + max_count
    time.sleep(0.5)

Уже скачано 0 записей
Уже скачано 100 записей
Уже скачано 200 записей
Уже скачано 300 записей
Уже скачано 400 записей
Уже скачано 500 записей
Уже скачано 600 записей
Уже скачано 700 записей
Уже скачано 800 записей
Уже скачано 900 записей
Уже скачано 1000 записей
Уже скачано 1100 записей
Уже скачано 1200 записей
Уже скачано 1300 записей
Уже скачано 1400 записей
Уже скачано 1500 записей
Уже скачано 1600 записей
Уже скачано 1700 записей
Уже скачано 1800 записей
Уже скачано 1900 записей
Уже скачано 2000 записей
Уже скачано 2100 записей
Уже скачано 2200 записей
Уже скачано 2300 записей
Уже скачано 2400 записей
Уже скачано 2500 записей
Уже скачано 2600 записей
Уже скачано 2700 записей
Уже скачано 2800 записей
Уже скачано 2900 записей
Уже скачано 3000 записей
Уже скачано 3100 записей
Уже скачано 3200 записей
Уже скачано 3300 записей
Уже скачано 3400 записей
Уже скачано 3500 записей
Уже скачано 3600 записей
Уже скачано 3700 записей
Уже скачано 3800 записей
Уже скачано 3900 записей
Уже скачано 4000 записей
Уже скачано 4100 записей
Уже скачано 4200 записей
Уже скачано 4300 записей
Уже скачано 4400 записей
Уже скачано 4500 записей
Уже скачано 4600 записей
Уже скачано 4700 записей
Уже скачано 4800 записей
Уже скачано 4900 записей
Уже скачано 5000 записей
Уже скачано 5100 записей
Уже скачано 5200 записей
Уже скачано 5300 записей
Уже скачано 5400 записей
Уже скачано 5500 записей
Уже скачано 5600 записей
Уже скачано 5700 записей
Уже скачано 5800 записей
Уже скачано 5900 записей
Уже скачано 6000 записей
Уже скачано 6100 записей
Уже скачано 6200 записей
Уже скачано 6300 записей
Уже скачано 6400 записей
Уже скачано 6500 записей
Уже скачано 6600 записей
Уже скачано 6700 записей
Уже скачано 6800 записей
Уже скачано 6900 записей
Уже скачано 7000 записей
Уже скачано 7100 записей
Уже скачано 7200 записей
Уже скачано 7300 записей
Уже скачано 7400 записей
Уже скачано 7500 записей
Уже скачано 7600 записей
Уже скачано 7700 записей
Уже скачано 7800 записей
Уже скачано 7900 записей
Уже скачано 8000 записей
Уже скачано 8100 записей

In [51]:
print('Кол-во записей:', len(posts))

Кол-во записей: 8124

In [52]:
posts.head()

,id,from_id,owner_id,date,marked_as_ads,is_favorite,post_type,text,is_pinned,attachments,...,views,donut,short_text_rate,carousel_offset,hash,edited,copy_history,signer_id,zoom_text,geo
0,87574,-51890028,-51890028,1654100160,0,False,post,Запишитесь на занятия в Skyeng через [https://...,1.0,"[{'type': 'photo', 'photo': {'album_id': -7, '...",...,{'count': 16392},{'is_donut': False},0.8,0.0,88yb3MU6YtB6e-8b6PNen4LYgsuR,NaN,NaN,NaN,NaN,NaN
1,87818,-51890028,-51890028,1655227017,0,False,post,"Вы же не станете покупать вещь, не примерив ее...",NaN,"[{'type': 'photo', 'photo': {'album_id': -7, '...",...,{'count': 4664},{'is_donut': False},0.8,0.0,Q7cNXxyXx2nfDWTvc__tRxQIMMkh,1.655275e+09,NaN,NaN,NaN,NaN
2,87801,-51890028,-51890028,1655136023,0,False,post,"Как ни крути, разговор о погоде — один из прос...",NaN,"[{'type': 'photo', 'photo': {'album_id': -7, '...",...,{'count': 34397},{'is_donut': False},0.8,0.0,4OSndHLr7P8Lwgw9YlQsDwwH_F7j,NaN,NaN,NaN,NaN,NaN
3,87795,-51890028,-51890028,1655040397,0,False,post,На дорогу многие из нас тратят не меньше часа ...,NaN,"[{'type': 'photo', 'photo': {'album_id': -7, '...",...,{'count': 32377},{'is_donut': False},0.8,0.0,ScQnSBs6ULPGzAmJZPMXo67m1XRR,1.655041e+09,NaN,NaN,NaN,NaN
4,87792,-51890028,-51890028,1655031958,0,False,post,,NaN,"[{'type': 'video', 'video': {'can_comment': 1,...",...,{'count': 6789},{'is_donut': False},0.8,NaN,3ebicjBdw6C6mQJYevHbwAAipJ5Q,NaN,NaN,NaN,NaN,NaN



Выгружаем 50 самых популярных постов. Метрикой популярности мы считаем сумму лайков, репостов и комментариев.

In [53]:
posts['comments_count'] = posts['comments'].apply(lambda x: x['count'])
posts['likes_count'] = posts['likes'].apply(lambda x: x['count'])
posts['reposts_count'] = posts['reposts'].apply(lambda x: x['count'])
posts.head()

,id,from_id,owner_id,date,marked_as_ads,is_favorite,post_type,text,is_pinned,attachments,...,carousel_offset,hash,edited,copy_history,signer_id,zoom_text,geo,comments_count,likes_count,reposts_count
0,87574,-51890028,-51890028,1654100160,0,False,post,Запишитесь на занятия в Skyeng через [https://...,1.0,"[{'type': 'photo', 'photo': {'album_id': -7, '...",...,0.0,88yb3MU6YtB6e-8b6PNen4LYgsuR,NaN,NaN,NaN,NaN,NaN,2,13,2
1,87818,-51890028,-51890028,1655227017,0,False,post,"Вы же не станете покупать вещь, не примерив ее...",NaN,"[{'type': 'photo', 'photo': {'album_id': -7, '...",...,0.0,Q7cNXxyXx2nfDWTvc__tRxQIMMkh,1.655275e+09,NaN,NaN,NaN,NaN,0,11,5
2,87801,-51890028,-51890028,1655136023,0,False,post,"Как ни крути, разговор о погоде — один из прос...",NaN,"[{'type': 'photo', 'photo': {'album_id': -7, '...",...,0.0,4OSndHLr7P8Lwgw9YlQsDwwH_F7j,NaN,NaN,NaN,NaN,NaN,2,102,93
3,87795,-51890028,-51890028,1655040397,0,False,post,На дорогу многие из нас тратят не меньше часа ...,NaN,"[{'type': 'photo', 'photo': {'album_id': -7, '...",...,0.0,ScQnSBs6ULPGzAmJZPMXo67m1XRR,1.655041e+09,NaN,NaN,NaN,NaN,0,30,14
4,87792,-51890028,-51890028,1655031958,0,False,post,,NaN,"[{'type': 'video', 'video': {'can_comment': 1,...",...,NaN,3ebicjBdw6C6mQJYevHbwAAipJ5Q,NaN,NaN,NaN,NaN,NaN,2,16,0

In [54]:
# заполняем данными столбец с суммой по всем активностям

posts['activity'] =posts['comments_count']+ posts['likes_count']+posts['reposts_count']
posts.head()

,id,from_id,owner_id,date,marked_as_ads,is_favorite,post_type,text,is_pinned,attachments,...,hash,edited,copy_history,signer_id,zoom_text,geo,comments_count,likes_count,reposts_count,activity
0,87574,-51890028,-51890028,1654100160,0,False,post,Запишитесь на занятия в Skyeng через [https://...,1.0,"[{'type': 'photo', 'photo': {'album_id': -7, '...",...,88yb3MU6YtB6e-8b6PNen4LYgsuR,NaN,NaN,NaN,NaN,NaN,2,13,2,17
1,87818,-51890028,-51890028,1655227017,0,False,post,"Вы же не станете покупать вещь, не примерив ее...",NaN,"[{'type': 'photo', 'photo': {'album_id': -7, '...",...,Q7cNXxyXx2nfDWTvc__tRxQIMMkh,1.655275e+09,NaN,NaN,NaN,NaN,0,11,5,16
2,87801,-51890028,-51890028,1655136023,0,False,post,"Как ни крути, разговор о погоде — один из прос...",NaN,"[{'type': 'photo', 'photo': {'album_id': -7, '...",...,4OSndHLr7P8Lwgw9YlQsDwwH_F7j,NaN,NaN,NaN,NaN,NaN,2,102,93,197
3,87795,-51890028,-51890028,1655040397,0,False,post,На дорогу многие из нас тратят не меньше часа ...,NaN,"[{'type': 'photo', 'photo': {'album_id': -7, '...",...,ScQnSBs6ULPGzAmJZPMXo67m1XRR,1.655041e+09,NaN,NaN,NaN,NaN,0,30,14,44
4,87792,-51890028,-51890028,1655031958,0,False,post,,NaN,"[{'type': 'video', 'video': {'can_comment': 1,...",...,3ebicjBdw6C6mQJYevHbwAAipJ5Q,NaN,NaN,NaN,NaN,NaN,2,16,0,18

In [55]:
posts_50 = posts.sort_values(by='activity', ascending = False).head(50)
posts_50.head()

,id,from_id,owner_id,date,marked_as_ads,is_favorite,post_type,text,is_pinned,attachments,...,hash,edited,copy_history,signer_id,zoom_text,geo,comments_count,likes_count,reposts_count,activity
23,63081,-51890028,-51890028,1602590409,0,False,post,КОНКУРС! Выиграйте уроки английского и бьюти-б...,NaN,"[{'type': 'photo', 'photo': {'album_id': -7, '...",...,aU6ZxJGqwPw9qmbR3eIBv55_roJ8,NaN,NaN,NaN,NaN,NaN,10962,117,2,11081
70,25259,-51890028,-51890028,1554800244,0,False,post,Через 15 дней вы накачаете пресс и выучите анг...,NaN,"[{'type': 'photo', 'photo': {'album_id': -7, '...",...,sBXeNq83EOqKMyE9olg1Suz7IcLM,1.554800e+09,NaN,NaN,NaN,NaN,239,7004,1358,8601
17,977,-51890028,-51890028,1416930109,0,False,post,100 полезных английских фраз\nЭти фразы выруча...,NaN,"[{'type': 'photo', 'photo': {'album_id': -7, '...",...,bPlHuGG0j5jkD__jL08PZZNucZdq,1.416991e+09,NaN,NaN,NaN,NaN,0,4012,973,4985
58,75933,-51890028,-51890028,1604923204,0,False,post,КОНКУРС! Выиграйте уроки английского и боксы с...,NaN,"[{'type': 'photo', 'photo': {'album_id': -7, '...",...,PAQ1EgneK1Dw0bxzo79jLfnydgd2,NaN,NaN,NaN,NaN,NaN,2891,133,6,3030
49,42960,-51890028,-51890028,1568444249,0,False,post,😑Предлоги в английском — больная тема для всех...,NaN,"[{'type': 'photo', 'photo': {'album_id': -7, '...",...,_1C4cI0VzcJJnKlucuxPWsg00kKP,1.568449e+09,NaN,NaN,NaN,NaN,50,1929,444,2423



Почистим данные, сохраняем результат

In [56]:
posts_50 = posts_50[:50]
postsTable = posts_50[['id', 'date', 'text', 'comments_count', 'likes_count', 'reposts_count', 'activity']]
postsTable.head()

,id,date,text,comments_count,likes_count,reposts_count,activity
23,63081,1602590409,КОНКУРС! Выиграйте уроки английского и бьюти-б...,10962,117,2,11081
70,25259,1554800244,Через 15 дней вы накачаете пресс и выучите анг...,239,7004,1358,8601
17,977,1416930109,100 полезных английских фраз\nЭти фразы выруча...,0,4012,973,4985
58,75933,1604923204,КОНКУРС! Выиграйте уроки английского и боксы с...,2891,133,6,3030
49,42960,1568444249,😑Предлоги в английском — больная тема для всех...,50,1929,444,2423

In [57]:
import time
from datetime import datetime

In [58]:
postsTable['date'] = pd.to_datetime(postsTable['date'], unit = 's')

C:\Users\konuh.a\AppData\Local\Temp/ipykernel_14188/2450011663.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  postsTable['date'] = pd.to_datetime(postsTable['date'], unit = 's')

In [59]:
postsTable

,id,date,text,comments_count,likes_count,reposts_count,activity
23,63081,2020-10-13 12:00:09,КОНКУРС! Выиграйте уроки английского и бьюти-б...,10962,117,2,11081
70,25259,2019-04-09 08:57:24,Через 15 дней вы накачаете пресс и выучите анг...,239,7004,1358,8601
17,977,2014-11-25 15:41:49,100 полезных английских фраз\nЭти фразы выруча...,0,4012,973,4985
58,75933,2020-11-09 12:00:04,КОНКУРС! Выиграйте уроки английского и боксы с...,2891,133,6,3030
49,42960,2019-09-14 06:57:29,😑Предлоги в английском — больная тема для всех...,50,1929,444,2423
14,48883,2019-11-22 09:25:57,"Кот Виктор показывает, как стал причиной сканд...",54,1623,203,1880
21,31067,2019-06-23 14:55:35,Играем в слова. У кого словарный запас больше?...,1634,135,3,1772
54,55740,2020-04-18 11:00:00,Без фразовых глаголов можно понимать только са...,36,1396,272,1704
82,51793,2020-02-07 06:43:07,"Английский снова сводит нас с ума, 😉и ему вооб...",111,1383,197,1691
8,57606,2020-05-13 12:31:02,Готовы ли вы к жизни в англоговорящем городе? ...,84,1480,116,1680
74,60584,2020-07-30 10:26:49,Подписывайтесь на [club51890028|Skyeng],26,1457,157,1640
15,46599,2019-10-01 08:00:01,📚🤓Ну вы поняли.👇🏻😉,44,1426,81,1551
18,53495,2020-03-11 14:00:14,,66,1423,57,1546
46,61198,2020-08-17 06:03:00,Все самые главные фразовые глаголы в карточках...,18,1207,234,1459
3,49309,2019-11-27 07:00:03,Методисты онлайн-школы Skyeng составили чек-ли...,35,1176,230,1441
69,58506,2020-06-06 12:27:51,Простое объяснение всех времен в английском. \...,104,1185,140,1429
40,1955,2015-02-23 16:15:25,60 английских фраз на все случаи жизни\nТакого...,0,1059,230,1289
17,53529,2020-03-11 16:00:11,"🎁 Ребят, мы тут конкурс затеяли. Подарим 2 БЕС...",661,586,8,1255
19,59728,2020-07-04 14:04:32,58 фразовых глаголов на все случаи жизни! \n\n...,69,954,201,1224
29,29630,2019-06-19 07:23:59,"Теперь вы знаете, как отвечать:\n– How are you...",132,1024,31,1187
45,80953,2020-12-30 08:56:44,Новогодний словарик: 36 праздничных английских...,0,655,517,1172
72,1071,2014-12-02 17:20:00,100 английских фраз для путешествий\nЭти фразы...,0,883,273,1156
98,49521,2019-11-29 14:01:00,✅Приставки открывают сразу много новых слов пр...,8,907,184,1099
59,52465,2020-02-19 07:00:06,Наши методисты составили чек-лист: какие темы ...,26,889,175,1090
38,83458,2021-02-27 14:09:00,58 фразовых глаголов 🔥🇬🇧\n\nМы собрали в одну ...,3,519,524,1046
96,54766,2020-03-25 06:35:14,👉 Без паники!,38,893,27,958
58,50315,2019-12-21 07:49:17,Skyeng объясняет как не запутаться в английско...,20,827,99,946
70,82904,2021-02-12 07:47:27,5 важных предлогов в английском 🔥🇬🇧\n\nПредлог...,8,474,457,939
35,83507,2021-03-01 09:14:38,Не путайте предлоги: полезные карточки 🇬🇧📌\n\n...,0,455,477,932
33,56848,2020-04-30 14:27:10,Идея на майские.💡80 иностранных фильмов для пр...,47,727,121,895
48,25874,2019-04-19 14:17:00,"Раз в неделю, мы и [club130552184|Topsify] пре...",27,811,26,864
4,61837,2020-09-09 12:10:03,Английские предлоги не поддаются каким-либо пр...,6,703,138,847
19,83644,2021-03-09 14:05:00,Синонимы к фразе «I like» 😍 Сохраняйте себе и ...,11,569,259,839
45,59310,2020-06-20 16:16:25,"Синонимы к прилагательным happy, good и beauti...",10,694,128,832
24,30758,2019-06-21 15:28:00,Мы любим разбирать Карди Би. Это как будто выу...,79,696,53,828
25,57238,2020-05-04 06:17:00,"Хвалите себя чаще! \n\n❓ Расскажите, как вы пр...",22,719,70,811
78,41520,2019-08-31 07:00:08,😃Билли Айлиш проспала премию Video Music Award...,58,727,24,809
64,58770,2020-06-09 12:04:49,Напишите в комментариях цифру от 1 до 7. Фраза...,74,664,71,809
17,81596,2021-01-19 07:19:00,"В чем разница между словами say, tell, speak и...",2,443,364,809
1,5078,2015-12-15 11:20:21,Skyeng Steps — бесплатный курс разговорного ан...,0,658,133,791
66,80671,2020-12-22 17:11:00,5 самых важных времен в английском \n\nВ англи...,0,396,382,778
35,61440,2020-08-24 05:46:00,"Английские синонимы, в которых уже заложено ус...",9,664,102,775
16,23617,2019-03-16 12:28:00,Дэни собрал для вас самый топовый американский...,28,673,72,773
37,28925,2019-06-15 15:17:31,Вы можете учить английский вообще бесплатно и ...,196,557,2,755
60,83020,2021-02-17 08:28:23,В чем разница между must и should? А когда исп...,32,393,329,754
36,59439,2020-06-24 15:20:00,В вашу видео-копилку на выходные. 👇🏻,32,654,63,749
68,25267,2019-04-09 10:22:00,Дэни собрал для вас самый топовый американский...,41,643,52,736
68,84862,2021-06-03 07:59:34,Английские предлоги не поддаются каким-либо пр...,0,360,374,734
42,59374,2020-06-22 12:43:32,"Фразовые глаголы со словом get, которые должен...",11,622,99,732
68,27559,2019-06-01 13:33:31,Мы сегодня встали пораньше и убрали тонну мусо...,93,636,0,729

In [60]:
import csv
postsTable.to_csv('posts_50.csv')